### ISSUE TITLE
Can there be a NIN opener with Doton pre-pull (then hide)?

### ISSUE THREAD

**Issue by Chunkybutt** [Rikudouu/XIVOpeners#23]

**Comment by alondite6** [comment]
While you're at it, can you update the standard opener to reflect the one posted in the Balance's guide? https://i.imgur.com/uEnxluT.png

Thank you!

**Comment by chadit** [comment]
there is already there, the standard opener handles this

**Comment by Rikudouu** [comment]
Should be fixed in ffd05ae
