### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Zancerc** [Rikudouu/XIVOpeners#28]
Hey, got that callstack error with 1.8.0 - with 1.7.2 its working for bard.
![ffxiv_26042020_155236_759](https://user-images.githubusercontent.com/40495336/80309630-886fc980-87d6-11ea-88d4-aca43aea4acf.png)

**Comment by Rikudouu** [comment]
You need TensorCore (free) installed from the store if you use v1.8.0
