### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Evo1979** [Rikudouu/XIVOpeners#29]
installed this as directed but when set nothing happens it just auto attacks no matter what job im on am i missing something ?

**Comment by Rikudouu** [comment]
does the gui show up in game?

**Comment by Evo1979** [comment]
yes that shows up i select to run for the job im on but nothing happens it just stands there auto attacking with reaction attacks only this is the same for what ever job i go on but main jobs i run are PLD, BRD, NIN, MCH

**Comment by Evo1979** [comment]
sorted the problem turns out for some reason Tensorcore had been removed yet i didnt remove it.
